<?php
/**
 * @var \Mageplaza\SocialShare\Block\FloatDisplay $block
 */
?>

<?php if($block->isThisPageEnable()):?>
<div><b>Inline Bottom</b></div>
<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
  <a class="a2a_button_facebook"></a>
  <a class="a2a_button_twitter"></a>
  <a class="a2a_button_google_plus"></a>
  <a class="a2a_button_pinterest"></a>
  <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
</div>

<script type="text/javascript">require(['https://static.addtoany.com/menu/page.js']);</script>
<?php endif; ?>