<?php
/**
 * @var \Mageplaza\SocialShare\Block\FloatDisplay $block
 */
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Mageplaza_SocialShare/js/float": {
                    "iconColor": "<?php echo /* @escapeNotVerified */ $block->_helperData->getIconColor() ?>",
                    "buttonColor": "<?php echo /* @escapeNotVerified */ $block->_helperData->getButtonColor() ?>",
                    "backgroundColor": "<?php echo /* @escapeNotVerified */ $block->_helperData->getBackgroundColor() ?>",
                    "borderRadius": "<?php echo /* @escapeNotVerified */ $block->_helperData->getBorderRadius() ?>"
                }
            }
        }
</script>

<script>
    var a2a_config = a2a_config || {};
    a2a_config.exclude_services = ["myspace", "linkedin", "whatsapp", "facebook"];
</script>